#!/bin/bash
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
pip install packages/django-bootstrap3
pip install packages/django-tables2

mkdir media static_files
# python manage.py collectstatic
python manage.py makemigrations
python manage.py migrate
echo "Setup Complete."